#!/usr/bin/env python

import lxml.etree as etree

def main():

	xml = etree.parse('idn-tables-1.0.rng')
	root = xml.getroot()

	for e in root.xpath('//comment()|//a:documentation', namespaces={'a':'http://relaxng.org/ns/compatibility/annotations/1.0'}):
		p = e.getparent()
		if p is not None:
			p.remove(e)
	print etree.tostring(root, pretty_print=True)

main()
